---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jdap-jenkins-slaves
  name: jdap-jenkins-slave1
  namespace: jd-jdap
spec:
  containers:
    - image: hub-pub.jdcloud.com/jdap/jdap-jenkins-slave:v0.0.3
      args: ["slave", "10.233.45.199", "slave1", "9b28fa883b93eb872ac0a2b02af14516ca8e3baa8b43673d861aac9aeadaea6b"]
      imagePullPolicy: Always
      name: jdap-jenkins-slave1
      ports:
        - containerPort: 80
          name: port-80
          protocol: TCP
        - containerPort: 8080
          name: port-8080
          protocol: TCP
        - containerPort: 22
          name: port-22
          protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 512Mi
        requests:
          cpu: "1"
          memory: 512Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
    - name: jcr-pull-secret
    - name: tpaas-itg
  restartPolicy: Always
  schedulerName: default-scheduler
  terminationGracePeriodSeconds: 30
